// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementApplicationDAL.Data;

#nullable disable

namespace SchoolManagementApplicationDAL.Migrations
{
    [DbContext(typeof(AuthDBContext))]
    [Migration("20260503071818_Auth Db creation in Prod db v1.0")]
    partial class AuthDbcreationinProddbv10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "55ed1dd3-fab2-45d9-8315-f44c9b1a56b6",
                            ConcurrencyStamp = "55ed1dd3-fab2-45d9-8315-f44c9b1a56b6",
                            Name = "Guest",
                            NormalizedName = "Guest"
                        },
                        new
                        {
                            Id = "92c45b3a-aa65-42d2-8676-948b220b720c",
                            ConcurrencyStamp = "92c45b3a-aa65-42d2-8676-948b220b720c",
                            Name = "Student",
                            NormalizedName = "Student"
                        },
                        new
                        {
                            Id = "b6104460-b1bd-486f-a168-1d2e91149f32",
                            ConcurrencyStamp = "b6104460-b1bd-486f-a168-1d2e91149f32",
                            Name = "Employee",
                            NormalizedName = "Employee"
                        },
                        new
                        {
                            Id = "66274e81-f4fa-4b15-b60f-1c8ad8318c7b",
                            ConcurrencyStamp = "66274e81-f4fa-4b15-b60f-1c8ad8318c7b",
                            Name = "Educator",
                            NormalizedName = "Educator"
                        },
                        new
                        {
                            Id = "28b43410-0ccc-42d8-9388-13e50fb304a9",
                            ConcurrencyStamp = "28b43410-0ccc-42d8-9388-13e50fb304a9",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "b311b544-0176-4dbc-8dca-d6acc8fb78d4",
                            ConcurrencyStamp = "b311b544-0176-4dbc-8dca-d6acc8fb78d4",
                            Name = "SuperAdmin",
                            NormalizedName = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "54b604ca-3373-4e7e-979f-a4ac0f530459",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a7785965-83c4-4edd-8786-ed83fa962843",
                            Email = "superadmin@skr.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@SKR.COM",
                            NormalizedUserName = "SUPERADMIN@SKR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAPyTSAjlGbhzWi6GuHRyKvuoWrV0EcVt4HZAlk6L9n5DAWEPxK0Brr+5hD6PkqJfw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7430e3da-03f3-4d5e-9b95-7dc08637ca6b",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@skr.com"
                        },
                        new
                        {
                            Id = "091608d1-4929-4dc7-b570-8e4eb1504b97",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "991244b8-0e0a-4a6e-b72f-4f2ec92b6768",
                            Email = "employee@skr.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYEE@SKR.COM",
                            NormalizedUserName = "EMPLOYEE@SKR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENRC1GmDNL0GgPs2K1seGZVpKqhVrbZm7D93mqdvWhM09iuoQULz1zc4CbBe3XE46A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "64f09265-5d87-4faa-ac76-6aabb0a513e3",
                            TwoFactorEnabled = false,
                            UserName = "employee@skr.com"
                        },
                        new
                        {
                            Id = "f23fbc7b-5ab1-4364-9752-feae53928ec4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "850ce79a-2bfe-4d59-a15a-9c66033dd7b5",
                            Email = "educator@skr.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EDUCATOR@SKR.COM",
                            NormalizedUserName = "EDUCATOR@SKR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFBjclD0hIKlWTTn6OVC7HlCpMIWqHnlP3jYHLad5pKLZlOVHMxmNP/rMAM8YyrHyg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "92888ee8-7907-4ff0-b2e7-db75be936289",
                            TwoFactorEnabled = false,
                            UserName = "educator@skr.com"
                        },
                        new
                        {
                            Id = "891373ed-0d7d-4e63-80a3-9e560ce553d9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "165542d8-76a0-4e5c-81a4-f0a8ff7b9bb0",
                            Email = "student@skr.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT@SKR.COM",
                            NormalizedUserName = "STUDENT@SKR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFd3apG0MBZ538lCykIKJPP1mx93xywU0Pu+/+NUplfMc9dreW3gdqzyD3H6oIlSUQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "97c3fa1b-ebbc-4ac0-ac1f-f83c7c43dca2",
                            TwoFactorEnabled = false,
                            UserName = "student@skr.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "54b604ca-3373-4e7e-979f-a4ac0f530459",
                            RoleId = "55ed1dd3-fab2-45d9-8315-f44c9b1a56b6"
                        },
                        new
                        {
                            UserId = "54b604ca-3373-4e7e-979f-a4ac0f530459",
                            RoleId = "92c45b3a-aa65-42d2-8676-948b220b720c"
                        },
                        new
                        {
                            UserId = "54b604ca-3373-4e7e-979f-a4ac0f530459",
                            RoleId = "b6104460-b1bd-486f-a168-1d2e91149f32"
                        },
                        new
                        {
                            UserId = "54b604ca-3373-4e7e-979f-a4ac0f530459",
                            RoleId = "66274e81-f4fa-4b15-b60f-1c8ad8318c7b"
                        },
                        new
                        {
                            UserId = "54b604ca-3373-4e7e-979f-a4ac0f530459",
                            RoleId = "b311b544-0176-4dbc-8dca-d6acc8fb78d4"
                        },
                        new
                        {
                            UserId = "091608d1-4929-4dc7-b570-8e4eb1504b97",
                            RoleId = "b6104460-b1bd-486f-a168-1d2e91149f32"
                        },
                        new
                        {
                            UserId = "091608d1-4929-4dc7-b570-8e4eb1504b97",
                            RoleId = "55ed1dd3-fab2-45d9-8315-f44c9b1a56b6"
                        },
                        new
                        {
                            UserId = "f23fbc7b-5ab1-4364-9752-feae53928ec4",
                            RoleId = "66274e81-f4fa-4b15-b60f-1c8ad8318c7b"
                        },
                        new
                        {
                            UserId = "f23fbc7b-5ab1-4364-9752-feae53928ec4",
                            RoleId = "55ed1dd3-fab2-45d9-8315-f44c9b1a56b6"
                        },
                        new
                        {
                            UserId = "891373ed-0d7d-4e63-80a3-9e560ce553d9",
                            RoleId = "92c45b3a-aa65-42d2-8676-948b220b720c"
                        },
                        new
                        {
                            UserId = "891373ed-0d7d-4e63-80a3-9e560ce553d9",
                            RoleId = "55ed1dd3-fab2-45d9-8315-f44c9b1a56b6"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
