// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementApplicationDAL.Data;

#nullable disable

namespace SchoolManagementApplicationDAL.Migrations
{
    [DbContext(typeof(AuthDBContext))]
    [Migration("20260502210016_Added New Roles")]
    partial class AddedNewRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fe342b15-5975-41d8-83cb-d7b1b8b8b152",
                            ConcurrencyStamp = "fe342b15-5975-41d8-83cb-d7b1b8b8b152",
                            Name = "Guest",
                            NormalizedName = "Guest"
                        },
                        new
                        {
                            Id = "31371bcb-ae05-4d27-967b-b27047aecbf7",
                            ConcurrencyStamp = "31371bcb-ae05-4d27-967b-b27047aecbf7",
                            Name = "Student",
                            NormalizedName = "Student"
                        },
                        new
                        {
                            Id = "568a834c-3049-492e-ae5d-09b7dc39db19",
                            ConcurrencyStamp = "568a834c-3049-492e-ae5d-09b7dc39db19",
                            Name = "Employee",
                            NormalizedName = "Employee"
                        },
                        new
                        {
                            Id = "f473d18b-b0ff-4606-9e80-8dda261019c9",
                            ConcurrencyStamp = "f473d18b-b0ff-4606-9e80-8dda261019c9",
                            Name = "Educator",
                            NormalizedName = "Educator"
                        },
                        new
                        {
                            Id = "ac9ff895-6c6a-4653-a52d-f42947a30810",
                            ConcurrencyStamp = "ac9ff895-6c6a-4653-a52d-f42947a30810",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "adb1abf0-c8dd-45a6-b760-bc61c30c4fef",
                            ConcurrencyStamp = "adb1abf0-c8dd-45a6-b760-bc61c30c4fef",
                            Name = "Principal",
                            NormalizedName = "Principal"
                        },
                        new
                        {
                            Id = "ddb9168c-704f-44af-8403-8def10a67eb1",
                            ConcurrencyStamp = "ddb9168c-704f-44af-8403-8def10a67eb1",
                            Name = "Director",
                            NormalizedName = "Director"
                        },
                        new
                        {
                            Id = "d2436ebc-8ff2-4a4a-931b-0f311f58f4da",
                            ConcurrencyStamp = "d2436ebc-8ff2-4a4a-931b-0f311f58f4da",
                            Name = "SuperAdmin",
                            NormalizedName = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b520fa96-b94d-4feb-b6d6-cc9141ca0b3c",
                            Email = "superadmin@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@SKR91.COM",
                            NormalizedUserName = "SUPERADMIN@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKM4f3LE9XR+eLGFpZcOdk8LZZCG61HOkAca2hB7SMj1THWWkzhOEAYxP1++o4ykFg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "29f91817-2b06-4a3c-bc97-183661672257",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@skr91.com"
                        },
                        new
                        {
                            Id = "25973b30-2677-46d7-9b72-584ede7a5c6e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5abef6da-efb0-4647-b0f1-d0f33d2724c0",
                            Email = "principal@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PRINCIPAL@SKR91.COM",
                            NormalizedUserName = "PRINCIPAL@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFU5o20UOCHNh6upFctNRYAxAe2GnzRGGAmpRHXTOMnErQbW98i4g/8BDaZbZxxzaA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a151e065-da0d-441c-b49a-1559af20af75",
                            TwoFactorEnabled = false,
                            UserName = "principal@skr91.com"
                        },
                        new
                        {
                            Id = "7c604289-9d4d-4051-90b2-5e7b8982d6ae",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e417e571-c254-4f4d-810c-d5bdc8e11243",
                            Email = "educator@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EDUCATOR@SKR91.COM",
                            NormalizedUserName = "EDUCATOR@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOg1S2iCQhSt0CYEqPRIxC6y7B3uTAf2H9itJSTrLIfo2lrjjWAKdNVfMLdn2b2Opw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "28d761c0-532b-49c7-9f7f-ad6643c9e10a",
                            TwoFactorEnabled = false,
                            UserName = "educator@skr91.com"
                        },
                        new
                        {
                            Id = "6cffae1f-2c3a-4588-b176-7e6691a5c1b2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "716fbf90-db32-4ea3-935e-cd292a061e9a",
                            Email = "educator@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EDUCATOR@SKR91.COM",
                            NormalizedUserName = "EDUCATOR@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHLTSO8ovBVTyUM1vrkwpk3R9+wRJ+FUPPyO+H594pXjP2hB7hsOCKHEv7cYcUK/TA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "54020ee4-e436-4cbb-8329-a8f4c8f5734c",
                            TwoFactorEnabled = false,
                            UserName = "educator@skr91.com"
                        },
                        new
                        {
                            Id = "63da928e-9896-4f73-8c1b-0ea5a9500b80",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fbc8cad9-8cb9-4655-89e6-8f830aa197ab",
                            Email = "student@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT@SKR91.COM",
                            NormalizedUserName = "STUDENT@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOAoAvYi2K7j8KL3zORZ8LZHiOci2VnBjg6W0GLFj/3TDGgxzq/mQJBhXyp78KChsA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "af378a48-afa3-4df6-afd8-37dd23164784",
                            TwoFactorEnabled = false,
                            UserName = "student@skr91.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "ac9ff895-6c6a-4653-a52d-f42947a30810"
                        },
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "f473d18b-b0ff-4606-9e80-8dda261019c9"
                        },
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "568a834c-3049-492e-ae5d-09b7dc39db19"
                        },
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        },
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "adb1abf0-c8dd-45a6-b760-bc61c30c4fef"
                        },
                        new
                        {
                            UserId = "25973b30-2677-46d7-9b72-584ede7a5c6e",
                            RoleId = "ac9ff895-6c6a-4653-a52d-f42947a30810"
                        },
                        new
                        {
                            UserId = "25973b30-2677-46d7-9b72-584ede7a5c6e",
                            RoleId = "f473d18b-b0ff-4606-9e80-8dda261019c9"
                        },
                        new
                        {
                            UserId = "25973b30-2677-46d7-9b72-584ede7a5c6e",
                            RoleId = "568a834c-3049-492e-ae5d-09b7dc39db19"
                        },
                        new
                        {
                            UserId = "25973b30-2677-46d7-9b72-584ede7a5c6e",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        },
                        new
                        {
                            UserId = "7c604289-9d4d-4051-90b2-5e7b8982d6ae",
                            RoleId = "568a834c-3049-492e-ae5d-09b7dc39db19"
                        },
                        new
                        {
                            UserId = "7c604289-9d4d-4051-90b2-5e7b8982d6ae",
                            RoleId = "f473d18b-b0ff-4606-9e80-8dda261019c9"
                        },
                        new
                        {
                            UserId = "7c604289-9d4d-4051-90b2-5e7b8982d6ae",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        },
                        new
                        {
                            UserId = "6cffae1f-2c3a-4588-b176-7e6691a5c1b2",
                            RoleId = "f473d18b-b0ff-4606-9e80-8dda261019c9"
                        },
                        new
                        {
                            UserId = "6cffae1f-2c3a-4588-b176-7e6691a5c1b2",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        },
                        new
                        {
                            UserId = "63da928e-9896-4f73-8c1b-0ea5a9500b80",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
