// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementApplicationDAL.Data;

#nullable disable

namespace SchoolManagementApplicationDAL.Migrations
{
    [DbContext(typeof(AuthDBContext))]
    [Migration("20260502163253_AuthDB Tables creation")]
    partial class AuthDBTablescreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "31371bcb-ae05-4d27-967b-b27047aecbf7",
                            ConcurrencyStamp = "31371bcb-ae05-4d27-967b-b27047aecbf7",
                            Name = "Student",
                            NormalizedName = "Student"
                        },
                        new
                        {
                            Id = "568a834c-3049-492e-ae5d-09b7dc39db19",
                            ConcurrencyStamp = "568a834c-3049-492e-ae5d-09b7dc39db19",
                            Name = "Employee",
                            NormalizedName = "Employee"
                        },
                        new
                        {
                            Id = "f473d18b-b0ff-4606-9e80-8dda261019c9",
                            ConcurrencyStamp = "f473d18b-b0ff-4606-9e80-8dda261019c9",
                            Name = "Educator",
                            NormalizedName = "Educator"
                        },
                        new
                        {
                            Id = "ac9ff895-6c6a-4653-a52d-f42947a30810",
                            ConcurrencyStamp = "ac9ff895-6c6a-4653-a52d-f42947a30810",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "d2436ebc-8ff2-4a4a-931b-0f311f58f4da",
                            ConcurrencyStamp = "d2436ebc-8ff2-4a4a-931b-0f311f58f4da",
                            Name = "SuperAdmin",
                            NormalizedName = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3493eb6b-6b12-49a2-8e33-68cbdb43936e",
                            Email = "director@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DIRECTOR@SKR91.COM",
                            NormalizedUserName = "DIRECTOR@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED4dfkkiGyKEoMyx+BxzDvEhRi4EQPh6BYOUlWPms8G1vFPJcKBX/rWH+dcgfSXGuQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "178934b1-53bd-49ae-9b29-6db3550922e2",
                            TwoFactorEnabled = false,
                            UserName = "director@skr91.com"
                        },
                        new
                        {
                            Id = "6cffae1f-2c3a-4588-b176-7e6691a5c1b2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "461c137f-0b79-418a-8541-c5f451db28d3",
                            Email = "educator@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EDUCATOR@SKR91.COM",
                            NormalizedUserName = "EDUCATOR@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMpgHvUspJ0myTicxZP8iivAGkiMTBmiUptQWDu38iI/oRiYcoRqKdvSYtzJ8fNxJw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "18915fe2-b0a2-4620-aabe-25cb09366f63",
                            TwoFactorEnabled = false,
                            UserName = "educator@skr91.com"
                        },
                        new
                        {
                            Id = "63da928e-9896-4f73-8c1b-0ea5a9500b80",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8e2cc943-1187-43e5-b2d8-342f506b0fd3",
                            Email = "student@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT@SKR91.COM",
                            NormalizedUserName = "STUDENT@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPRm3YEudyMLh4HQqaueudZr5D+xxK9lE1sbbemp5pGL75VGJKIazhLbXRHZGxmpVA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b07dc701-6dfe-4258-90f8-844b6a89cc79",
                            TwoFactorEnabled = false,
                            UserName = "student@skr91.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "ac9ff895-6c6a-4653-a52d-f42947a30810"
                        },
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "f473d18b-b0ff-4606-9e80-8dda261019c9"
                        },
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "568a834c-3049-492e-ae5d-09b7dc39db19"
                        },
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        },
                        new
                        {
                            UserId = "6cffae1f-2c3a-4588-b176-7e6691a5c1b2",
                            RoleId = "f473d18b-b0ff-4606-9e80-8dda261019c9"
                        },
                        new
                        {
                            UserId = "6cffae1f-2c3a-4588-b176-7e6691a5c1b2",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        },
                        new
                        {
                            UserId = "63da928e-9896-4f73-8c1b-0ea5a9500b80",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
