// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementApplicationDAL.Data;

#nullable disable

namespace SchoolManagementApplicationDAL.Migrations
{
    [DbContext(typeof(AuthDBContext))]
    [Migration("20260503065442_Authentication Tables creation")]
    partial class AuthenticationTablescreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "55ed1dd3-fab2-45d9-8315-f44c9b1a56b6",
                            ConcurrencyStamp = "55ed1dd3-fab2-45d9-8315-f44c9b1a56b6",
                            Name = "Guest",
                            NormalizedName = "Guest"
                        },
                        new
                        {
                            Id = "92c45b3a-aa65-42d2-8676-948b220b720c",
                            ConcurrencyStamp = "92c45b3a-aa65-42d2-8676-948b220b720c",
                            Name = "Student",
                            NormalizedName = "Student"
                        },
                        new
                        {
                            Id = "b6104460-b1bd-486f-a168-1d2e91149f32",
                            ConcurrencyStamp = "b6104460-b1bd-486f-a168-1d2e91149f32",
                            Name = "Employee",
                            NormalizedName = "Employee"
                        },
                        new
                        {
                            Id = "66274e81-f4fa-4b15-b60f-1c8ad8318c7b",
                            ConcurrencyStamp = "66274e81-f4fa-4b15-b60f-1c8ad8318c7b",
                            Name = "Educator",
                            NormalizedName = "Educator"
                        },
                        new
                        {
                            Id = "28b43410-0ccc-42d8-9388-13e50fb304a9",
                            ConcurrencyStamp = "28b43410-0ccc-42d8-9388-13e50fb304a9",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "b311b544-0176-4dbc-8dca-d6acc8fb78d4",
                            ConcurrencyStamp = "b311b544-0176-4dbc-8dca-d6acc8fb78d4",
                            Name = "SuperAdmin",
                            NormalizedName = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "54b604ca-3373-4e7e-979f-a4ac0f530459",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "88f84d3d-2e1a-443d-86fa-09822ce7829f",
                            Email = "superadmin@skr.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@SKR.COM",
                            NormalizedUserName = "SUPERADMIN@SKR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED4uW/mG4Eu96hLpOC4G124Rjuc1x1vSPPBHRpTlQDqhge3IX/LvKbzRUUkWvXSSwg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ce99cf48-50c3-4ccb-9e1d-eeaa9a27d7db",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@skr.com"
                        },
                        new
                        {
                            Id = "091608d1-4929-4dc7-b570-8e4eb1504b97",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "acfc2d8c-a562-44d8-8178-309be220cbeb",
                            Email = "employee@skr.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYEE@SKR.COM",
                            NormalizedUserName = "EMPLOYEE@SKR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJnfU4lf8ar6ObdI5y8TXezo/R2fnAE1iXA3QQnw6QyvkHOt5kWL6aHAlLMI/DRXCg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d0845750-e473-4461-9bc9-491f815310c7",
                            TwoFactorEnabled = false,
                            UserName = "employee@skr.com"
                        },
                        new
                        {
                            Id = "f23fbc7b-5ab1-4364-9752-feae53928ec4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7143fc23-eb36-4996-baf9-903393c12831",
                            Email = "educator@skr.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EDUCATOR@SKR.COM",
                            NormalizedUserName = "EDUCATOR@SKR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMdg+uIWWq/4NPo/m2T3dar0ogQC6ZXdWmh4zl+L1wknn9KbsKx61L7Jlnn5HxcI+Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d53d0c90-0872-4a24-82f7-9a42c53bb713",
                            TwoFactorEnabled = false,
                            UserName = "educator@skr.com"
                        },
                        new
                        {
                            Id = "891373ed-0d7d-4e63-80a3-9e560ce553d9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "efd378be-da27-413d-a3fb-688c58a968e8",
                            Email = "student@skr.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT@SKR.COM",
                            NormalizedUserName = "STUDENT@SKR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG90VYBc1i2Js4z79lKBEfMIAI/whfeqBY7UQdgYE/6cRhQ+MgENzkUcmFtoC2QlRw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e09eed45-7456-4172-bd1d-2b6560b647ca",
                            TwoFactorEnabled = false,
                            UserName = "student@skr.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "54b604ca-3373-4e7e-979f-a4ac0f530459",
                            RoleId = "28b43410-0ccc-42d8-9388-13e50fb304a9"
                        },
                        new
                        {
                            UserId = "54b604ca-3373-4e7e-979f-a4ac0f530459",
                            RoleId = "66274e81-f4fa-4b15-b60f-1c8ad8318c7b"
                        },
                        new
                        {
                            UserId = "54b604ca-3373-4e7e-979f-a4ac0f530459",
                            RoleId = "b6104460-b1bd-486f-a168-1d2e91149f32"
                        },
                        new
                        {
                            UserId = "54b604ca-3373-4e7e-979f-a4ac0f530459",
                            RoleId = "92c45b3a-aa65-42d2-8676-948b220b720c"
                        },
                        new
                        {
                            UserId = "54b604ca-3373-4e7e-979f-a4ac0f530459",
                            RoleId = "55ed1dd3-fab2-45d9-8315-f44c9b1a56b6"
                        },
                        new
                        {
                            UserId = "091608d1-4929-4dc7-b570-8e4eb1504b97",
                            RoleId = "b6104460-b1bd-486f-a168-1d2e91149f32"
                        },
                        new
                        {
                            UserId = "091608d1-4929-4dc7-b570-8e4eb1504b97",
                            RoleId = "55ed1dd3-fab2-45d9-8315-f44c9b1a56b6"
                        },
                        new
                        {
                            UserId = "f23fbc7b-5ab1-4364-9752-feae53928ec4",
                            RoleId = "92c45b3a-aa65-42d2-8676-948b220b720c"
                        },
                        new
                        {
                            UserId = "f23fbc7b-5ab1-4364-9752-feae53928ec4",
                            RoleId = "55ed1dd3-fab2-45d9-8315-f44c9b1a56b6"
                        },
                        new
                        {
                            UserId = "891373ed-0d7d-4e63-80a3-9e560ce553d9",
                            RoleId = "92c45b3a-aa65-42d2-8676-948b220b720c"
                        },
                        new
                        {
                            UserId = "891373ed-0d7d-4e63-80a3-9e560ce553d9",
                            RoleId = "55ed1dd3-fab2-45d9-8315-f44c9b1a56b6"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
