// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementApplicationDAL.Data;

#nullable disable

namespace SchoolManagementApplicationDAL.Migrations
{
    [DbContext(typeof(AuthDBContext))]
    [Migration("20260502210932_Added New User Roles")]
    partial class AddedNewUserRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fe342b15-5975-41d8-83cb-d7b1b8b8b152",
                            ConcurrencyStamp = "fe342b15-5975-41d8-83cb-d7b1b8b8b152",
                            Name = "Guest",
                            NormalizedName = "Guest"
                        },
                        new
                        {
                            Id = "31371bcb-ae05-4d27-967b-b27047aecbf7",
                            ConcurrencyStamp = "31371bcb-ae05-4d27-967b-b27047aecbf7",
                            Name = "Student",
                            NormalizedName = "Student"
                        },
                        new
                        {
                            Id = "568a834c-3049-492e-ae5d-09b7dc39db19",
                            ConcurrencyStamp = "568a834c-3049-492e-ae5d-09b7dc39db19",
                            Name = "Employee",
                            NormalizedName = "Employee"
                        },
                        new
                        {
                            Id = "f473d18b-b0ff-4606-9e80-8dda261019c9",
                            ConcurrencyStamp = "f473d18b-b0ff-4606-9e80-8dda261019c9",
                            Name = "Educator",
                            NormalizedName = "Educator"
                        },
                        new
                        {
                            Id = "ac9ff895-6c6a-4653-a52d-f42947a30810",
                            ConcurrencyStamp = "ac9ff895-6c6a-4653-a52d-f42947a30810",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "adb1abf0-c8dd-45a6-b760-bc61c30c4fef",
                            ConcurrencyStamp = "adb1abf0-c8dd-45a6-b760-bc61c30c4fef",
                            Name = "Principal",
                            NormalizedName = "Principal"
                        },
                        new
                        {
                            Id = "ddb9168c-704f-44af-8403-8def10a67eb1",
                            ConcurrencyStamp = "ddb9168c-704f-44af-8403-8def10a67eb1",
                            Name = "Director",
                            NormalizedName = "Director"
                        },
                        new
                        {
                            Id = "d2436ebc-8ff2-4a4a-931b-0f311f58f4da",
                            ConcurrencyStamp = "d2436ebc-8ff2-4a4a-931b-0f311f58f4da",
                            Name = "SuperAdmin",
                            NormalizedName = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6c6b3b3b-47b3-4013-8e9e-9ad191f2174c",
                            Email = "superadmin@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@SKR91.COM",
                            NormalizedUserName = "SUPERADMIN@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECJEQvinok0FQub1/ToEhP6waAk6de+UsBsR2VhR3EQfGNLJS+RyJ107T7fgVs1rJg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dcf2eba8-181f-40ea-a9ad-c768f8f974b7",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@skr91.com"
                        },
                        new
                        {
                            Id = "25973b30-2677-46d7-9b72-584ede7a5c6e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1bf6d442-844d-4423-b2dc-3548b57fda17",
                            Email = "principal@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PRINCIPAL@SKR91.COM",
                            NormalizedUserName = "PRINCIPAL@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO11TwdOhvi2eacIiAEughNYSoi9BGy81Pc5Q7IeTSuMilqVVgqnm/r29rKNUZ8FRQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b0974086-5caf-4d6a-bb75-36e285c78dff",
                            TwoFactorEnabled = false,
                            UserName = "principal@skr91.com"
                        },
                        new
                        {
                            Id = "7c604289-9d4d-4051-90b2-5e7b8982d6ae",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6fd34750-b9ed-4e05-a7a2-92008d4b88ea",
                            Email = "employee@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYEE@SKR91.COM",
                            NormalizedUserName = "EMPLOYEE@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEj3I5eTSqhqSYq8hptudrSQpkoYoEcEbTgN6ergprNuXc1cUL8U8vjLrbnqBZ5+xA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3568e607-69b5-460a-9eb9-331c142f7737",
                            TwoFactorEnabled = false,
                            UserName = "employee@skr91.com"
                        },
                        new
                        {
                            Id = "6cffae1f-2c3a-4588-b176-7e6691a5c1b2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "08b74805-e683-4000-86b6-58ba824de888",
                            Email = "educator@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EDUCATOR@SKR91.COM",
                            NormalizedUserName = "EDUCATOR@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAOSe0Ih7rV8DBChoXDvgDxZkJJiNoMKJitRGHPWsq1plDv2TygdAvW6MXtXJcfBhg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2527bc41-7960-4ef9-9d97-9bca5f204903",
                            TwoFactorEnabled = false,
                            UserName = "educator@skr91.com"
                        },
                        new
                        {
                            Id = "63da928e-9896-4f73-8c1b-0ea5a9500b80",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca2f348c-be34-4649-b8bb-0e8dbf7bdeea",
                            Email = "student@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT@SKR91.COM",
                            NormalizedUserName = "STUDENT@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDIhK/h+b9wOSVwrFpCAnr5uGSokMB13dqbgslk7JMG149trY09O5jVkPj3x9QhYQA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a5248305-4021-49bc-a0f0-c3b9da4b3e47",
                            TwoFactorEnabled = false,
                            UserName = "student@skr91.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "ac9ff895-6c6a-4653-a52d-f42947a30810"
                        },
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "f473d18b-b0ff-4606-9e80-8dda261019c9"
                        },
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "568a834c-3049-492e-ae5d-09b7dc39db19"
                        },
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        },
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "adb1abf0-c8dd-45a6-b760-bc61c30c4fef"
                        },
                        new
                        {
                            UserId = "25973b30-2677-46d7-9b72-584ede7a5c6e",
                            RoleId = "ac9ff895-6c6a-4653-a52d-f42947a30810"
                        },
                        new
                        {
                            UserId = "25973b30-2677-46d7-9b72-584ede7a5c6e",
                            RoleId = "f473d18b-b0ff-4606-9e80-8dda261019c9"
                        },
                        new
                        {
                            UserId = "25973b30-2677-46d7-9b72-584ede7a5c6e",
                            RoleId = "568a834c-3049-492e-ae5d-09b7dc39db19"
                        },
                        new
                        {
                            UserId = "25973b30-2677-46d7-9b72-584ede7a5c6e",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        },
                        new
                        {
                            UserId = "7c604289-9d4d-4051-90b2-5e7b8982d6ae",
                            RoleId = "568a834c-3049-492e-ae5d-09b7dc39db19"
                        },
                        new
                        {
                            UserId = "7c604289-9d4d-4051-90b2-5e7b8982d6ae",
                            RoleId = "f473d18b-b0ff-4606-9e80-8dda261019c9"
                        },
                        new
                        {
                            UserId = "7c604289-9d4d-4051-90b2-5e7b8982d6ae",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        },
                        new
                        {
                            UserId = "6cffae1f-2c3a-4588-b176-7e6691a5c1b2",
                            RoleId = "f473d18b-b0ff-4606-9e80-8dda261019c9"
                        },
                        new
                        {
                            UserId = "6cffae1f-2c3a-4588-b176-7e6691a5c1b2",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        },
                        new
                        {
                            UserId = "63da928e-9896-4f73-8c1b-0ea5a9500b80",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
