// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementApplicationDAL.Data;

#nullable disable

namespace SchoolManagementApplicationDAL.Migrations
{
    [DbContext(typeof(AuthDBContext))]
    partial class AuthDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fe342b15-5975-41d8-83cb-d7b1b8b8b152",
                            ConcurrencyStamp = "fe342b15-5975-41d8-83cb-d7b1b8b8b152",
                            Name = "Guest",
                            NormalizedName = "Guest"
                        },
                        new
                        {
                            Id = "31371bcb-ae05-4d27-967b-b27047aecbf7",
                            ConcurrencyStamp = "31371bcb-ae05-4d27-967b-b27047aecbf7",
                            Name = "Student",
                            NormalizedName = "Student"
                        },
                        new
                        {
                            Id = "568a834c-3049-492e-ae5d-09b7dc39db19",
                            ConcurrencyStamp = "568a834c-3049-492e-ae5d-09b7dc39db19",
                            Name = "Employee",
                            NormalizedName = "Employee"
                        },
                        new
                        {
                            Id = "f473d18b-b0ff-4606-9e80-8dda261019c9",
                            ConcurrencyStamp = "f473d18b-b0ff-4606-9e80-8dda261019c9",
                            Name = "Educator",
                            NormalizedName = "Educator"
                        },
                        new
                        {
                            Id = "ac9ff895-6c6a-4653-a52d-f42947a30810",
                            ConcurrencyStamp = "ac9ff895-6c6a-4653-a52d-f42947a30810",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "adb1abf0-c8dd-45a6-b760-bc61c30c4fef",
                            ConcurrencyStamp = "adb1abf0-c8dd-45a6-b760-bc61c30c4fef",
                            Name = "Principal",
                            NormalizedName = "Principal"
                        },
                        new
                        {
                            Id = "ddb9168c-704f-44af-8403-8def10a67eb1",
                            ConcurrencyStamp = "ddb9168c-704f-44af-8403-8def10a67eb1",
                            Name = "Director",
                            NormalizedName = "Director"
                        },
                        new
                        {
                            Id = "d2436ebc-8ff2-4a4a-931b-0f311f58f4da",
                            ConcurrencyStamp = "d2436ebc-8ff2-4a4a-931b-0f311f58f4da",
                            Name = "SuperAdmin",
                            NormalizedName = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6c7f3765-bb15-48e8-ab9d-46219bff8765",
                            Email = "superadmin@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@SKR91.COM",
                            NormalizedUserName = "SUPERADMIN@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKY+dfruecCIaISo7LyfFPFbD8PKm5krmUlEcZl3PXKeTRrx8SRrFWHDSHMcC2nKMw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8b94016f-6b12-401d-8db7-857a62e78c8a",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@skr91.com"
                        },
                        new
                        {
                            Id = "25973b30-2677-46d7-9b72-584ede7a5c6e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3b5e557b-ccd7-42c2-8bda-f3bbd608d638",
                            Email = "principal@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PRINCIPAL@SKR91.COM",
                            NormalizedUserName = "PRINCIPAL@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBBICsihamscRTT7JF2eTIE8R9mfraPX12TiH37/f66m3Z8boezBkDvadDp/Q+aOdg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0c7c24f9-ea10-48d6-b22b-d34c50b57068",
                            TwoFactorEnabled = false,
                            UserName = "principal@skr91.com"
                        },
                        new
                        {
                            Id = "7c604289-9d4d-4051-90b2-5e7b8982d6ae",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ae82068a-5f33-43a8-b150-7d49156806a3",
                            Email = "employee@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYEE@SKR91.COM",
                            NormalizedUserName = "EMPLOYEE@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEP0fR88gW1aef6bu/UOZy9k0syAIZi+nygJiva4pJhPGkYD+He9gCGMYgLdpaNuVjg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "db61b194-5930-4136-b5fd-f5af3de7dfdb",
                            TwoFactorEnabled = false,
                            UserName = "employee@skr91.com"
                        },
                        new
                        {
                            Id = "6cffae1f-2c3a-4588-b176-7e6691a5c1b2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a138492d-33bf-484c-ab41-20773a4cff60",
                            Email = "faculty@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "FACULTY@SKR91.COM",
                            NormalizedUserName = "FACULTY@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJDvBv8NJc4cDHE/tB/JTIpe+epkqcrqQcEDOMgy8Yd1MZ4FBs1DKJ2Bsr+ekeIB/g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "83e39569-30e5-4a79-98d7-952104361ed0",
                            TwoFactorEnabled = false,
                            UserName = "faculty@skr91.com"
                        },
                        new
                        {
                            Id = "63da928e-9896-4f73-8c1b-0ea5a9500b80",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7948de41-e08b-41ff-a95d-98da13a4b11d",
                            Email = "students@skr91.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENTS@SKR91.COM",
                            NormalizedUserName = "STUDENTS@SKR91.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHFyLINysV70MyJpZn27uVPVdM3BmaBtXFrmSfQJQn4Ieh2lZRo7YVdr5VFFBAIEKQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2f5d08f8-a9f1-40a3-80ec-e801b9762b65",
                            TwoFactorEnabled = false,
                            UserName = "students@skr91.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "ac9ff895-6c6a-4653-a52d-f42947a30810"
                        },
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "f473d18b-b0ff-4606-9e80-8dda261019c9"
                        },
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "568a834c-3049-492e-ae5d-09b7dc39db19"
                        },
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        },
                        new
                        {
                            UserId = "4a1f05ea-ca6d-45e7-b558-82150290af0b",
                            RoleId = "adb1abf0-c8dd-45a6-b760-bc61c30c4fef"
                        },
                        new
                        {
                            UserId = "25973b30-2677-46d7-9b72-584ede7a5c6e",
                            RoleId = "ac9ff895-6c6a-4653-a52d-f42947a30810"
                        },
                        new
                        {
                            UserId = "25973b30-2677-46d7-9b72-584ede7a5c6e",
                            RoleId = "f473d18b-b0ff-4606-9e80-8dda261019c9"
                        },
                        new
                        {
                            UserId = "25973b30-2677-46d7-9b72-584ede7a5c6e",
                            RoleId = "568a834c-3049-492e-ae5d-09b7dc39db19"
                        },
                        new
                        {
                            UserId = "25973b30-2677-46d7-9b72-584ede7a5c6e",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        },
                        new
                        {
                            UserId = "7c604289-9d4d-4051-90b2-5e7b8982d6ae",
                            RoleId = "568a834c-3049-492e-ae5d-09b7dc39db19"
                        },
                        new
                        {
                            UserId = "7c604289-9d4d-4051-90b2-5e7b8982d6ae",
                            RoleId = "f473d18b-b0ff-4606-9e80-8dda261019c9"
                        },
                        new
                        {
                            UserId = "7c604289-9d4d-4051-90b2-5e7b8982d6ae",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        },
                        new
                        {
                            UserId = "6cffae1f-2c3a-4588-b176-7e6691a5c1b2",
                            RoleId = "f473d18b-b0ff-4606-9e80-8dda261019c9"
                        },
                        new
                        {
                            UserId = "6cffae1f-2c3a-4588-b176-7e6691a5c1b2",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        },
                        new
                        {
                            UserId = "63da928e-9896-4f73-8c1b-0ea5a9500b80",
                            RoleId = "31371bcb-ae05-4d27-967b-b27047aecbf7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
